apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: first-pod
      labels:
         app: myapp

    spec:
       containers:
        - name: nodejs
          image: quay.io/kubernetes-for-developers/nodejs:0.2.0

  replicas: 3
  selector:
    matchLabels:
      app: myapp